name: create_project_aro
description: "This package generates a professional directory structure for Flutter projects with a focus on clean architecture."
version: 0.0.4
homepage: https://arosistemas.com/
repository: https://github.com/ARoSistemas/create_project_aro

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
